# You can configure the addon's name in settings.gradle.kts
group=io.github.lyen.LogiTech
main-class=io.github.lyen.LogiTech.MyAddon
version=test
rebar.version=0.38.0
pylon.version=0.37.1-26.1

# Java installation configuration for Java 25
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=D:\\Java\\zulu25.34.17-ca-crac-jdk25.0.3-win_x64
# 替换为你的实际Java 25安装路径